url: https://jameshfisher.com
title: "Jim Fisher's blog"
author: "Jim Fisher"
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      justification: "I felt like it."
future: true
